#!/bin/bash

# Copyright (C) 2019 Jacques Labuschagne.
# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/gpl.txt

BEACON=/usr/local/bin/beacon

function error(){
    echo "$1" >&2
    exit 1
}

test -f /etc/lsb-release && source /etc/lsb-release

function install_dep_or_quit(){
    case "${DISTRIB_ID}" in
        Ubuntu)
            echo "Missing \"$1\"; trying to install" >&2
            apt-get update && apt-get install "$1" || error "Couldn't install $1"
            ;;
        *)
            error "Please install \"$1\" first"
            ;;
    esac
}

for i in curl screen; do
    DEP=$(which $i)
    if [ -z "${DEP}" ]; then
        install_dep_or_quit $i
    fi
done

echo "Installing beacon as ${BEACON}"

curl -s https://raw.githubusercontent.com/jlabusch/beacon/v1.0.5/beacon > ${BEACON} || error "Couldn't download beacon script"
chmod 755 ${BEACON}

exec ${BEACON} --webinstall


